# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import pydoc.core.conf


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'classifiers',
                'ordering': ('name',),
                'verbose_name': 'classifier',
            },
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, default='', help_text='the filename as provided by pypi', max_length=255)),
                ('file', models.FileField(blank=True, help_text='the distribution file (if it was mirrord locally)', max_length=255, null=True, upload_to=pydoc.core.conf.distribution_upload_to)),
                ('url', models.URLField(blank=True, help_text='the original url provided by pypi', max_length=255, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('md5_digest', models.CharField(blank=True, max_length=32)),
                ('filetype', models.CharField(choices=[('sdist', 'Source'), ('bdist_dumb', '"dumb" binary'), ('bdist_rpm', 'RPM'), ('bdist_wininst', 'MS Windows installer'), ('bdist_egg', 'Python Egg'), ('bdist_dmg', 'OS X Disk Image')], max_length=32)),
                ('pyversion', models.CharField(blank=True, choices=[('any', 'Any i.e. pure python'), ('2.1', '2.1'), ('2.2', '2.2'), ('2.3', '2.3'), ('2.4', '2.4'), ('2.5', '2.5'), ('2.6', '2.6'), ('2.7', '2.7'), ('3.0', '3.0'), ('3.1', '3.1'), ('3.2', '3.2')], max_length=16)),
                ('comment', models.TextField(blank=True, default='')),
                ('signature', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(blank=True, help_text='the time at which the package was uploaded (on pypi)', null=True)),
                ('mirrored_at', models.DateTimeField(blank=True, help_text='the time at which the package was downloaded to this mirror.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_from_external', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'distributions',
                'verbose_name': 'distribution',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('auto_hide', models.BooleanField(default=True)),
                ('updated_from_remote_at', models.DateTimeField(blank=True, null=True)),
                ('parsed_external_links_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'packages',
                'ordering': ['name'],
                'verbose_name': 'package',
                'get_latest_by': 'releases__latest',
            },
        ),
        migrations.CreateModel(
            name='PackageIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default='pypi', max_length=255, unique=True)),
                ('updated_from_remote_at', models.DateTimeField(blank=True, null=True)),
                ('xml_rpc_url', models.URLField(blank=True, default='http://pypi.python.org/pypi')),
                ('simple_url', models.URLField(blank=True, default='http://pypi.python.org/simple')),
            ],
            options={
                'verbose_name_plural': 'package indexes',
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=128)),
                ('metadata_version', models.CharField(default='1.0', max_length=64)),
                ('hidden', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_from_external', models.BooleanField(default=False)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='core.Package')),
            ],
            options={
                'verbose_name_plural': 'releases',
                'ordering': ['-created'],
                'verbose_name': 'release',
                'get_latest_by': 'created',
            },
        ),
        migrations.AddField(
            model_name='package',
            name='index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PackageIndex'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='core.Release'),
        ),
        migrations.AlterUniqueTogether(
            name='release',
            unique_together=set([('package', 'version')]),
        ),
        migrations.AlterUniqueTogether(
            name='distribution',
            unique_together=set([('release', 'filetype', 'pyversion')]),
        ),
    ]
