# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 00:40
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='package_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='packageindex',
            name='simple_url',
            field=models.URLField(blank=True, default='https://pypi.python.org/simple'),
        ),
        migrations.AlterField(
            model_name='packageindex',
            name='xml_rpc_url',
            field=models.URLField(blank=True, default='https://pypi.python.org/pypi'),
        ),
    ]
