# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 03:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161021_0040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='release',
            old_name='hidden',
            new_name='built',
        ),
    ]
