# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-06 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add-built'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='mirrored_at',
            field=models.DateTimeField(blank=True, help_text='The time the package was downloaded (here)', null=True),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, help_text='The time the package was uploaded (on pypi)', null=True),
        ),
    ]
