# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-06 20:26
from __future__ import unicode_literals

from django.db import migrations


def forwards_func(apps, schema_editor):
    # Add a default package index (Pypi)
    PackageIndex = apps.get_model("core", "PackageIndex")
    db_alias = schema_editor.connection.alias
    PackageIndex.using(db_alias).create()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170406_1926'),
    ]

    operations = [
        migrations.RunPython(forwards_func, None),
    ]
